name: Generate pages

on:
  workflow_dispatch:
    inputs:
        skipHashMatch:
          description: 'Setting to true will make sure pages are regenerated even if there is no change in the trains timetable'
          type: boolean
          default: false
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write

jobs:
  run-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodule
        run: git submodule update --remote --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        working-directory: timetable-generator
        run: npm ci

      - name: Apply SkipHashMatching setting if set
        if: github.event_name == 'workflow_dispatch' && inputs.skipHashMatch == true
        working-directory: timetable-generator
        run: |
          jq '.SkipHashMatching = true' src/settings.json > src/settings.tmp.json
          mv src/settings.tmp.json src/settings.json

      - name: Build timetable generator
        working-directory: timetable-generator
        run: npm run build

      - name: Copy files for generation
        run: |
          cp -r ./docs timetable-generator/output
          cp -r ./RunInfo timetable-generator/RunInfo

      - name: Generate timetables
        working-directory: timetable-generator
        run: npm run start

      - name: Copy files for upload
        run: |
          rm -rf ./docs
          cp -r timetable-generator/output ./docs
          rm -rf ./RunInfo
          cp -r timetable-generator/RunInfo ./RunInfo

      - name: Restore settings.json
        if: github.event_name == 'workflow_dispatch' && inputs.skipHashMatch == true
        run: git checkout -- timetable-generator/src/settings.json

      - name: Upload files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git diff --staged --quiet || git commit -m "Generation: $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
